name: SkycadeMissions
version: 1.4.1-SNAPSHOT
description: Skycade Missions
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycademissions.SkycadeMissionsPlugin
softdepend: []
depend: [SkycadeCore]