name: SkycadeMissions
version: 3.2.2-SNAPSHOT
description: Skycade Missions
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycademissions.SkycadeMissionsPlugin
softdepend: [SkycadeShop, SkycadeEnchants, SkycadeKitPvP, SkycadeSkyblock, Prison]
depend: [SkycadeCore]