name: SkycadeMissions
version: 3.1.7-SNAPSHOT
description: Skycade Missions
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycademissions.SkycadeMissionsPlugin
softdepend: [SkycadeShop, SkycadeEnchants, SkycadeKitPvP]
depend: [SkycadeCore]