name: SkycadeMissions
version: 1.4.5-SNAPSHOT
description: Skycade Missions
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycademissions.SkycadeMissionsPlugin
softdepend: [SkycadeShop, SkycadeEnchants]
depend: [SkycadeCore]