name: SkycadeMissions
version: 2.0.0-SNAPSHOT
description: Skycade Missions
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycademissions.SkycadeMissionsPlugin
softdepend: [SkycadeShop, SkycadeEnchants]
depend: [SkycadeCore]